/* automatically generated by rust-bindgen 0.63.0 */

pub const AT_SYSINFO_EHDR: i32 = 33;
pub const AT_MINSIGSTKSZ: i32 = 51;
pub const AT_VECTOR_SIZE_ARCH: i32 = 2;
pub const AT_NULL: i32 = 0;
pub const AT_IGNORE: i32 = 1;
pub const AT_EXECFD: i32 = 2;
pub const AT_PHDR: i32 = 3;
pub const AT_PHENT: i32 = 4;
pub const AT_PHNUM: i32 = 5;
pub const AT_PAGESZ: i32 = 6;
pub const AT_BASE: i32 = 7;
pub const AT_FLAGS: i32 = 8;
pub const AT_ENTRY: i32 = 9;
pub const AT_NOTELF: i32 = 10;
pub const AT_UID: i32 = 11;
pub const AT_EUID: i32 = 12;
pub const AT_GID: i32 = 13;
pub const AT_EGID: i32 = 14;
pub const AT_PLATFORM: i32 = 15;
pub const AT_HWCAP: i32 = 16;
pub const AT_CLKTCK: i32 = 17;
pub const AT_SECURE: i32 = 23;
pub const AT_BASE_PLATFORM: i32 = 24;
pub const AT_RANDOM: i32 = 25;
pub const AT_HWCAP2: i32 = 26;
pub const AT_EXECFN: i32 = 31;
