/* automatically generated by rust-bindgen 0.65.1 */

pub const DT_UNKNOWN: i32 = 0;
pub const DT_FIFO: i32 = 1;
pub const DT_CHR: i32 = 2;
pub const DT_DIR: i32 = 4;
pub const DT_BLK: i32 = 6;
pub const DT_REG: i32 = 8;
pub const DT_LNK: i32 = 10;
pub const DT_SOCK: i32 = 12;
