/* automatically generated by rust-bindgen 0.63.0 */

pub const _IOC_NRBITS: i32 = 8;
pub const _IOC_TYPEBITS: i32 = 8;
pub const _IOC_SIZEBITS: i32 = 14;
pub const _IOC_DIRBITS: i32 = 2;
pub const _IOC_NRMASK: i32 = 255;
pub const _IOC_TYPEMASK: i32 = 255;
pub const _IOC_SIZEMASK: i32 = 16383;
pub const _IOC_DIRMASK: i32 = 3;
pub const _IOC_NRSHIFT: i32 = 0;
pub const _IOC_TYPESHIFT: i32 = 8;
pub const _IOC_SIZESHIFT: i32 = 16;
pub const _IOC_DIRSHIFT: i32 = 30;
pub const _IOC_NONE: i32 = 0;
pub const _IOC_WRITE: i32 = 1;
pub const _IOC_READ: i32 = 2;
