/* automatically generated by rust-bindgen 0.66.1 */

pub type __kernel_sa_family_t = ::core::ffi::c_ushort;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_un {
    pub sun_family: __kernel_sa_family_t,
    pub sun_path: [::core::ffi::c_char; 108usize],
}
