/* automatically generated by rust-bindgen 0.69.1 */

pub const SEEK_SET: i32 = 0;
pub const SEEK_CUR: i32 = 1;
pub const SEEK_END: i32 = 2;
pub const SEEK_DATA: i32 = 3;
pub const SEEK_HOLE: i32 = 4;
pub const SEEK_MAX: i32 = 4;
pub const RENAME_NOREPLACE: i32 = 1;
pub const RENAME_EXCHANGE: i32 = 2;
pub const RENAME_WHITEOUT: i32 = 4;
