[package]
name = "linux-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bindgen = "0.65.1"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread", "fs"] }